
services:
  db:
    image: postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: metube
    volumes:
      - ./db-data:/var/lib/postgresql/data

  auth-service:
    image: auth-service
    build: ./
    ports:
      - "8084:8084"
    environment:
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: 1234

