server:
  port: 8084

spring:
  application:
    name: AUTH-SERVICE
  datasource:
    url: jdbc:postgresql://${DB_HOST:64.226.102.195}:5432/metube
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:8463}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect




eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://${EUREKA_HOST:localhost}:8761/eureka/}
  instance:
    preferIpAddress: true

springdoc:
  swagger-ui:
    config-url: /api/auth/v3/api-docs/swagger-config
    url: /api/auth/swagger-ui
    path: /api/auth/swagger-ui


jwt:
  secret: qwefklsdfj3roif134adsj14fdslkjf1234fiodwq
  accessTokenExpiration: 3600000
  refreshTokenExpiration: 86400000
